# All supported DynGames games and their settings
games:
  tntrun:
    enabled: true
    min_players: 2
    world:
      name: tntrun
      spawn:
        x: 1.0
        y: 1.0
        z: 1.0
        pitch: 1.0
        yaw: 1.0
      respawn:
        x: 1.0
        y: 1.0
        z: 1.0
        pitch: 1.0
        yaw: 1.0

# Chat options
chat:
  # Should DynGames format all chat messages?
  format-enabled: true
  # If format-enabled is true, use this format to display chat messages to users
  format: "&8[&c%level%&8]&7 - &r%username%&7: %message%"
  # If this is false, messages will be displayed only to players in the same world as the chatter
  global-chat: true

# Queue options
queue:
  # Location of queue, this is where players will be teleported when a game ends
  location:
    world: queue
    x: 1.0
    y: 1.0
    z: 1.0
    pitch: 1.0
    yaw: 1.0